language: node.js
node.js:
  -"7"
  -"8"
install:
  - npm install
script:
  - npm run build
after_success:
  - cd ./dist
  - curl -u $FTP_USER:$FTP_PASSWORD -T index.html ftp://r567tw.tw/public_html/tech/

